version:
  - 3.7
  - 3.7
  - 3.8
  - 3.9
  - 3.10
py_impl:
  - 73_pypy
  - cpython
  - cpython
  - cpython
  - cpython
cross_target_platform:
  - "linux-64"              # [linux64]
  - "linux-ppc64le"         # [linux64]
  - "linux-aarch64"         # [linux64]
  - "osx-64"
  - "osx-arm64"
zip_keys:
  - - version
    - py_impl
