version:
  - 3.8
  - 3.9
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12
  - 3.13
py_impl:
  - 73_pypy
  - 73_pypy
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  - cp313
channel_sources:
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge/label/python_rc,conda-forge
cross_target_platform:
  - "linux-64"              # [linux64]
  - "linux-ppc64le"         # [linux64]
  - "linux-aarch64"         # [linux64]
  - "osx-64"
  - "osx-arm64"
zip_keys:
  - - version
    - py_impl
    - channel_sources
