{% set build_number = "1" %}
package:
  name: cross-python
  version: {{ version }}

build:
  number: {{ build_number }}
  string: {{ build_number }}_cpython
  skip: True  # [win]
  run_exports:
    strong:
      - python {{ version }}.*

requirements:
  run:
    - python {{ version }}.* *_cpython
    - crossenv
    - rsync

test:
  commands:
    - test -f $PREFIX/etc/conda/activate.d/activate-cross-python.sh

about:
  home: https://github.com/conda-forge/cross-python-feedstock
  license: LicenseRef-OTHER
  summary: 'A meta-package to set up a cross compiling env for python in conda-build'

extra:
  recipe-maintainers:
    - isuruf
